### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by stephenc01** [jacker92/MIMHelper#1]
Hey, was there a reason to create this in C# and not native PS. IMO it will be easier for an organization to onboard this module if it did not need to be complied.

**Comment by jacker92** [comment]
Hi,

There is no particular reason why this is written in C# other than I find it little bit easier to work with than native PS. When I started building this, I thought it there would be more cmdlets overall and cmdlets that use dependencies that are only available in C#.

I might rewrite this in native PS in the future if I have extra time. Thanks for suggestion.

Jaakko
